### ISSUE TITLE
`l3build save` process doesn't stop when errors are encountered

### ISSUE THREAD

**Issue by dbitouze** [latex3/l3build#296] opened 2023-03-30 12:18 UTC
I wonder why the `l3build save` process doesn't stop when errors, even fatal ones, are encountered.

Indeed, suppose I create the following test file for a `\mycommand` command defined in a `mypackage` package I'm working on:
```latex
\input{regression-test.tex}
\documentclass{article}
\usepackage{mypackage}
\START
\showoutput
\mycommand{foo}
\vfil\break
\end{document}
```
Because of the fatal error (missing `\begin{document}`):

- not revealed during the `l3build save` process,
- hidden in the `.tlg` file,

hence potentially not detected, any further modification of `\mycommand` in `mypackage.sty` that should make the `l3build check` process fail, won't be detected.

Wouldn't be safer for the `l3build save` process to stop when errors are encountered?

**Comment by dbitouze** [comment] 2023-03-30 12:28
Wouldn't be possible to provide an option that would stop `l3build save` when errors are encountered?

**Comment by josephwright** [comment] 2023-03-30 12:32
We usually favour 'check one thing': if you look at most of the team's own test setups, there's usually one that just does 
```latex
\input{regression-test.tex}
\documentclass{article}
\START
\usepackage{mypackage}
\END
```
for exactly this purpose: testing if a package loads at all.

**Comment by FrankMittelbach** [comment] 2023-03-30 13:06
I propose to close this as it works as designed in in our opinion the design is solid, i.e., errors are conceptually part of tests and the concept is to always first check the test results (including the parts that have been deliberately suppressed in the tlg).

**Comment by dbitouze** [comment] 2023-03-31 07:53
@FrankMittelbach Could you explain a bit what you mean by “the concept is to always first check the test results”?

**Comment by u-fischer** [comment] 2023-03-31 08:57
@dbitouze after a save you should check the resulting log, tlg, pdf ... and consider if they show what you want them to show and what you want to test. If you are unsure, break you code deliberatly and then run l3build check and look if you get a failure.

**Comment by FrankMittelbach** [comment] 2023-04-01 11:15
> @FrankMittelbach Could you explain a bit what you mean by “the concept is to always first check the test results”?

@dbitouze when you write tests you need to manually verify that the result is exactly as you expect it and that the parts that are saved to the tlg (ie are not within \OMIT ... \TIMO) are showing what you expect to stay  if changes to code happen. l3build can't verify that for you, it can only ensure that the results are the same as the ones that you have manually verified at some point in the past.

The test may as well deliberately show errors (e.g., if you want to check how your code reacts to bad user input) and therefore l3build doesn't stop for tests that generate errors, but you have to ensure that these ares are "what you expect to happen" and that they end up in the tlg if they are supposed to be part of a test. 

For example, I normally make sure that my tests do *not* test the loading of a package, because that would mean that the test is always generating a diff whenever I change the code and the version changes. But, of course, one can make errors that only show while the package is loaded and therefore all of my package repositories have one test mypackage-000.lvt that does nothing other than loading the package and this time included into \START .... and I accept that this test needs updating whenever I change the code --- but then I need to *manually look at the diff*  before accepting it in order to ensure that the change is only in the parts that I expect to change and not suddenly in contain some different change, e.g., a typo in a csname.

When I intend to fix a bug, then I first write a test that shows the bug and its results and save that. Then I fix the bug and therefore the test should afterwards shows a difference (for example that the bug doesn't generate an error any longer or generates a proper error message or ...). then I resave the test to preserve the corected result so that in the future I see if the bug resurfaces because of other changes.

**Closed by FrankMittelbach** 2023-04-01 11:15 UTC
